obj-y = copter.o
obj-$(CONFIG_EMERGENCY) += emergency.o
obj-$(CONFIG_MOTOR) += motor_ctrl.o
obj-$(CONFIG_RC) += remote_control.o
obj-$(CONFIG_LC) += linux_client.o
obj-$(CONFIG_RC_COMMANDER) += rc_commander.o
obj-$(CONFIG_LC_COMMANDER) += linux_commander.o 
obj-$(CONFIG_DISPLAY) += display.o
